ALTER TABLE [dotnetnuke_dukes].[dnn_EngageEmployment_JobGroup]
    ADD CONSTRAINT [dnn_PK_EngageEmployment_JobGroup] PRIMARY KEY CLUSTERED ([JobGroupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

