ALTER TABLE [dotnetnuke_dukes].[dnn_EngageEmployment_Job]
    ADD CONSTRAINT [dnn_PK_EngageEmployment_Job] PRIMARY KEY CLUSTERED ([JobId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

