ALTER TABLE [dbo].[engage_EngageEmployment_Document]
    ADD CONSTRAINT [PK_engage_EngageEmployment_Document] PRIMARY KEY CLUSTERED ([ResumeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

